import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useCallback, useState } from "react";
import { useRef } from "react";
import { memo } from "react";
import { Button, Stack, Grid, ThemeProvider, Paper } from "@mui/material";
import theme from "@/themes";
import { bgcolor } from "@mui/system";
import { SignupForm } from "@/components/SignupForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Stack
          spacing={2}
          sx={{
            mx: 2,
            my: 2,
          }}
          alignItems="center"
        >
          <Button sx={{ flex: 1 }}>HELLO</Button>
          <Button sx={{ flex: 2 }}>HELLO</Button>
          <Button sx={{ flex: 3 }}>HELLO</Button>
          <ThemeProvider theme={theme}>
            <Button sx={{ m: 3 }} variant="contained">
              HELLO WORLD
              <Button sx={{ m: 6 }} variant="outlined">
                HELLO WORLD
                <Button sx={{ m: 3 }} variant="text">
                  HELLO WORLD
                </Button>
              </Button>
            </Button>
          </ThemeProvider>
        </Stack>
      </Head>
      <SignupForm />
    </>
  );
}
//ci sono anche variant outlined,text in ordine di "importanza
//alignItems serve ad allineare le cose come preferiamo, ad esempio center,flex-start,flex-end
